class CustomError(Exception):
    def __init__(self, n):
        super(Exception, self).__init__()
        self.n = n

try:
    raise CustomError(3)
except CustomError as c:
    print(c.n)
